name: Build Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.9
          channel: stable
          cache: true

      - name: Flutter Version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localization
        run: flutter gen-l10n

      - name: Build Debug APK (Play)
        run: |
         ./flutterw pub get
         ./flutterw build apk --debug -t lib/main_play.dart --flavor play

      - name: Build Debug APK (Izzy)
        run: |
         ./flutterw build apk --debug -t lib/main_izzy.dart --flavor izzy

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/*.apk
